### ISSUE TITLE
unable to change background color of dropdown list

### ISSUE THREAD

**Issue by LearningLadoo** [Faiza-Farooqui/Flutter-CustomizableDropDown#1]
the background color of dropdown list doesn't change from white.
I tried changing the canvas color in ThemeData but still it remains white.

widget-
AwesomeDropDown(
            isPanDown: _isPanDown,
            isBackPressedOrTouchedOutSide: _isBackPressedOrTouchedOutSide,
            dropDownBGColor: themeData.scaffoldBackgroundColor,
            dropDownOverlayBGColor: themeData.scaffoldBackgroundColor,
            padding: 8,
            dropDownIcon: Icon(
              Icons.arrow_drop_down,
              size: 23,
            ),
            elevation: 8,
            dropDownBorderRadius: 10,
            dropDownTopBorderRadius: 10,
            dropDownBottomBorderRadius: 10,
            dropDownIconBGColor: Colors.transparent,
            dropDownList: _list,
            selectedItem: _selectedItem,
            numOfListItemToShow: 4,
            selectedItemTextStyle: themeData.textTheme.headline2!,
            dropDownListTextStyle: themeData.textTheme.headline2!,
            onDropDownItemClick: (selectedItem) {
              _selectedItem = selectedItem;
            },
            dropStateChanged: (isOpened) {
              _isDropDownOpened = isOpened;
              if (!isOpened) {
                _isBackPressedOrTouchedOutSide = false;
              }
            },
          ),

**Comment by Faiza-Farooqui** [comment]
the issue you raised has been resolved now. Thank you
