### ISSUE TITLE
numOfListItemToShow doesn't take into account the dropDownListTextStyle

### ISSUE THREAD

**Issue by matiestrella** [Faiza-Farooqui/Flutter-CustomizableDropDown#2]
numOfListItemToShow doesn't take into account the dropDownListTextStyle, so when you want to use a bigger font ,the last item of the drop down list is not completely visible.
![image](https://user-images.githubusercontent.com/72713012/129459674-850a6169-630c-4f7b-bdec-35bc6d20cdf8.png)

**Comment by Faiza-Farooqui** [comment]
Hello,

this is the screenshot with size= 40. maybe it is your phone issue or what idk. can you please share some more detail about the scenario or any other useful info so I can guess the issue.

<img height="280px" src="https://user-images.githubusercontent.com/36657067/130216698-a7979b2c-5cab-4873-a1b1-74aac2f52d9e.jpeg">

**Comment by Faiza-Farooqui** [comment]
Ok. as you hadn't provide any sufficient info about the issue you opened so I am closing it here.
